homepage/urls.py
from django.conf.urls import url
from homepage import views

# TEMPLATE TAGGING
app_name = "homepage"
urlpatterns = [
    # url(r'^$', views.IndexViews.as_view(), name='index'), # not use CBV this time
    url(r'^$', views.index, name='index'),
    url(r'^complete/$', views.complete, name='complete'),  # Contact_result page
    url(r'^QandA/$', views.QandA, name='QandA'), # Q and A page
]

website/urls.py
from django.contrib import admin
from django.urls import path
from homepage import views
from django.conf.urls import include
from homepage import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
    path('', views.index, name="index"),
    path('', views.complete, name="complete"),
    path('', views.QandA, name="QandA"),
]

homepage/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

""" Post Q and A from Admin page """
class Topic(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=400)
    text = models.TextField()

    def __str__(self):
        return self.title

homepage/forms.py
from django import forms
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse
from django.forms import ModelForm

# from django.core.mail import send_main => メールの送信
# BadHeaderErrorは内容を改ざんするセキュリティ攻撃を検出した際に生成される

class ContactForm(forms.Form):
    subject = forms.CharField(label='Subject', max_length=100)
    sender = forms.EmailField(label='Email')
    message = forms.CharField(label='Message', widget=forms.Textarea)

homepage/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from .models import Topic
from .forms import ContactForm
from django.core.mail import EmailMessage

# Template Views with CBV
""""
class IndexView(TemplateView):
    template_name = 'homepage/index.html'
"""
# This time I use def instead...

# main page and response of contact

"""
def index(request):
    return render(request, "homepage/index.html")
"""

"""
def index(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['itstudent.jp@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('homepage/complete')
    return render(request, "homepage/index.html", {'form': form})
"""
def index(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            email = EmailMessage(
                                   from_email=sender,
                                   subject=subject,
                                   body=message,
                                   to=["itstudent.jp@gmail.com"],
                                   cc=[sender], # If you want to send more than 2 ppl, add their address here
                                   )

            try:
                email.send()
            except BadHeaderError:
                return HttpResponse('無効なヘッダーが見つかりました。')
            return redirect('homepage:complete')

    else:
        form = ContactForm()

    return render(request, 'homepage/index.html', {'form': form})

"""
「POST」されたフォームの内容を「form.is_valid()」で検証し正しければ「complete.html」に渡されるという記述。
"""

# Contact completed
def complete(request):
    return render(request, 'homepage/complete.html')

# Q and A
# Post from Admin page for Q and A
def QandA(request):
    queryset = Topic.objects.all()
    context = { "QandA":queryset }
    return render(request, 'homepage/QandA.html', context)

templates/homepage/QandA.html
{% extends "homepage/base.html" %}
{% load static %}

{% block contents %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>

    <!-- Q and A !-->
    <div class="QandA_form">
        <h1>Q and A</h1>
    </div>
    <div class="QandA_form">
        {% for context in QandA|slice:"10" %}
        <div class="Question">
            <h3>Q: {{ context.title }}</h3>
            <h4>{{ context.text }}</h4>
        </div>
        {% endfor %}
    </div>
    <br>
    <br>
    <br>
{% endblock %}

templates/homepage/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <!-- Responsive !-->
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> !-->
        <title>Base</title>
        <!-- CSS !-->
        <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />_
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <!-- google font !-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Chewy&display=swap" rel="stylesheet">
        <!-- BOOTSTRAP !-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <header>
            <h1 id="brand-name">TAKE ME TRAVEL✈︎</h1>
            <div class="main">
                <ul>
                    <li class="current"><a href="{% url 'homepage:index' %}">Home</a></li>
                    <li><a href="{% url 'homepage:index' %}#jump_about">About</a></li>
                    <li><a href="{% url 'homepage:index' %}#jump_service">Service</a></li>
                    <li><a href="{% url 'homepage:QandA' %}">Q&A</a></li>
                    <li><a href="{% url 'homepage:index' %}#jump_contact">Contact</a></li>
                </ul>
            </div>
        </header>

        {% block contents %}
        <!-- define contents (継承外) !-->
        {% endblock %}

    </body>

    <!-- footer contact !-->
    <a id="jump_contact">
    <footer class="footer-section">
        <div class="container">
            <div class="footer-cta pt-5 pb-5">
                <div class="row">
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <i class="fas fa-map-marker-alt"></i>
                            <div class="cta-text">
                                <h4>Find us</h4>
                                <span>00-000 XXXXX ,Warsaw, Poland</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <i class="fas fa-phone"></i>
                            <div class="cta-text">
                                <h4>Call us</h4>
                                <span>000-111-222</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <i class="far fa-envelope-open"></i>
                            <div class="cta-text">
                                <h4>Mail us</h4>
                                <span>mail@gmail.com</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- footer var !-->
            <nav>
                <ul>
                    <li><a href="{% url 'homepage:index' %}">Home</a></li>
                    <li><a href="{% url 'homepage:index' %}#jump_about">About</a></li>
                    <li><a href="{% url 'homepage:index' %}#jump_service">Service</a></li>
                    <li><a href="{% url 'homepage:QandA' %}">Q&A</a></li>
                    <li><a href="{% url 'homepage:index' %}#jump_contact">Contact</a></li>
                </ul>
            </nav>
        <!-- copy right  !-->
        <div class="copyright-area">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 text-center text-lg-left">
                        <div class="copyright-text">
                            <p>Copyright &copy; 2018, All Right Reserved <a href="https://codepen.io/anupkumar92/">Anup</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    </a>
</html>

templates/homepage/complete.html
{% extends "homepage/base.html" %}
{% load static %}

{% block contents %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>

    <!-- complete page !-->
    <div class="complete_form">
        <h1>Thank you for your contact! We have received.</h1>
        <h3><a href="{% url 'homepage:index' %}">Back to main page</a></h3>
    </div>
{% endblock %}

templates/homepage/index.html
{% extends "homepage/base.html" %}
{% load static %}

{% block contents %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>
    <!-- main page top !-->
    <div class="home_pic">
        <img src="{% static 'images/santorini.jpg' %}" alt="invalid">
        <div class="catch_phrase">
            <h1>Ready to explore the world?</h1>
            <p>Let's get out of the ordinary life and have new experience with us.<br>
                We are providing the best plan which perfectly suits you!
            </p>
            <h3><a href="{% url 'homepage:index' %}#jump_service">&nbsp;Check Our Service&nbsp;</a></h3>
        </div>
    </div>

    <!-- main page about us !-->
    <a id="jump_about">
    <div class="contents">
        <div class="left-column">
            <img src="{% static 'images/travel.jpg' %}" alt="invalid">
        </div>
        <div class="right-column">
            <h1>About Us</h1>
            <p><br>“Travel is the main thing you purchase that makes you more extravagant”.
                We, "at Take Me Travel", swear by this and put stock in satisfying travel dreams that make you perpetually rich constantly.
                We have been moving excellent encounters for a considerable length of time through our cutting-edge planned
                occasion bundles and other fundamental travel administrations. We rouse our clients to carry on with a rich life, brimming with extraordinary travel encounters.</p>
        </div>
    </div>
    </a>

    <!-- main page service table !-->
    <a id="jump_service">
    <div class="service_table">
        <div class="service_line"></div>
            <h2>20% OFF</h2>
            <div class="service_cards">
                <div class="discount_box">
                    <h3>Indonesia</h3>
                    <img src="{% static 'images/indonesia.jpg' %}" alt="invalid">
                    <h3><strike>2 nights $1000</strike></h3>
                    <h3>2 nights $800</h3>
                    <p>This is script. This is script. This is script. This is script.
                    This is script. This is script. This is script.</p>
                </div>
                <div class="discount_box">
                    <h3>Warsaw</h3>
                    <img src="{% static 'images/warsaw.jpg' %}" alt="invalid">
                    <h3><strike>2 nights $1200</strike></h3>
                    <h3>2 nights $960</h3>
                    <p>This is script. This is script. This is script. This is script.
                        This is script. This is script. This is script.</p>
                </div>
                <div class="discount_box">
                    <h3>London</h3>
                    <img src="{% static 'images/london.jpg' %}" alt="invalid">
                    <h3><strike>2 night $2000</strike></h3>
                    <h3>2 nights $1600</h3>
                    <p>This is script. This is script. This is script. This is script.
                    This is script. This is script. This is script.</p>
                </div>
            </div>
        <div class="service_button">
            <a href="" class="btn btn--red btn--radius btn--cubic"><h3>See More Options</h3><i class="fas fa-angle-right fa-position-right"></i></a>
        </div>
        <div class="service_line"></div>
    </div>

    <!-- Contact Us Form !-->
    <div class="pic_contact_form">
       <img src="{% static 'images/desert.jpg' %}" alt="invalid">
        <!--Contact form-->
        <div class="contact_form">
                 <h1>Ask Us Anything</h1>
                 <form method="post">
                {% csrf_token %}
                <!-- for文使って要素を取り出す-->
                {% for field in form %}
                     <div class="field">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                     </div>
                {% endfor %}
                    <button type="submit">Submit</button>
                </form>
        </div>
    </div>
{% endblock %}